namespace Vruchtgebruik.Api.Models
{
    /// <summary>
    /// Standard API error response model, used for all error cases (validation, server errors, etc).
    /// Provides consistent error information for clients, including trace and correlation IDs.
    /// </summary>
    internal class ApiErrorResponse
    {
        /// <summary>
        /// The error message describing what went wrong.
        /// </summary>
        public string Error { get; set; }= string.Empty;

        /// <summary>
        /// The error message describing what went wrong.
        /// </summary>
        public string TraceId { get; set; } = string.Empty;

        /// <summary>
        /// The correlation ID for the request, if your system uses one for cross-service/request correlation.
        /// This may be user-supplied (e.g., via an <c>X-Correlation-Id</c> header) or generated by middleware.
        /// </summary>
        public string CorrelationId { get; set; } = string.Empty;
    }
}
